apiVersion: v1
kind: Namespace
metadata:
  name: oracle23c

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracleords
  namespace: oracle23c
  labels:
    app: oracleords
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracleords
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: oracleords
    spec:
      imagePullSecrets:
        - name: docker-registry
      containers:
      - image: sin.ocir.io/hktwlab/oracleords:latest
        env:
        - name: ORACLE_ADMIN_USER
          value: "SYS"
        - name: ORACLE_SERVICE
          value: "freepdb1"
        - name: ORACLE_HOST
          value: "oracle23c-service.oracle23c.svc.cluster.local"
        - name: ORACLE_PORT
          value: "1521"
        - name: ORDS_USER
          value: "ORDS_PUBLIC_USER"
        - name: ORDS_PWD
          value: "abc123"
        - name: ORACLE_PWD
          value: "abc123"
        - name: ORDS_HTTPS_PORT
          value: "8443"
        - name: ORDS_HTTP_PORT
          value: "8080"
        - name: ORDS_CERT
          value: "/etc/ords/keystore/testing.mongodb.der"
        - name: ORDS_CERT_KEY
          value: "/etc/ords/keystore/testing.mongodb-key.der"
        - name: ORDS_HOME
          value: "/opt/ords"
        - name: ORDS_CONFIG
          value: "/etc/ords/config"
        name: oracleords
        ports:
        - containerPort: 8080
          name: oracleordshttp
        - containerPort: 8443
          name: oracleordshttps
        - containerPort: 27017
          name: oracleordsmongo
        volumeMounts:
          - name: ords-config-keystore
            mountPath: "/etc/ords/keystore"
        imagePullPolicy: Always
      volumes:
      - name: ords-config-keystore
        configMap:
          name: ords-config-keystore

---

apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJzaW4ub2Npci5pbyI6eyJhdXRoIjoiYUd0MGQyeGhZaTl2Y21GamJHVnBaR1Z1ZEdsMGVXTnNiM1ZrYzJWeWRtbGpaUzlsY21sakxtaHphV1ZvUUc5eVlXTnNaUzVqYjIwNmZWcHZkSDFSUkVSUFdqQXpkalY1ZlZsQ1QxOD0iLCJlbWFpbCI6ImVyaWMuaHNpZWhAb3JhY2xlLmNvbSIsInBhc3N3b3JkIjoifVpvdH1RRERPWjAzdjV5fVlCT18iLCJ1c2VybmFtZSI6ImhrdHdsYWIvb3JhY2xlaWRlbnRpdHljbG91ZHNlcnZpY2UvZXJpYy5oc2llaEBvcmFjbGUuY29tIn19fQ==
kind: Secret
metadata:
  name: docker-registry
  namespace: oracle23c
type: kubernetes.io/dockerconfigjson

---

apiVersion: v1
kind: Secret
metadata:
  namespace: oracle23c
  name: ordspassword
data:
  ordspassword: YWJjMTIzCg==

---

apiVersion: v1
kind: Service
metadata:
  name: oracleords-service
  namespace: oracle23c
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
    service.beta.kubernetes.io/oci-load-balancer-internal: "false"
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
    service.beta.kubernetes.io/oci-load-balancer-subnet1: "ocid1.subnet.oc1.ap-singapore-1.aaaaaaaatnutdfrcbyopfyasrqgof73lthkflgh5lbiwjejz62zliiy2yovq"
spec:
  selector:
    app: oracleords
  type: LoadBalancer
  ports:
  - name: oracleords
    protocol: TCP
    port: 27017
    targetPort: oracleordsmongo
  externalTrafficPolicy: Cluster
  sessionAffinity: None

